GET http://localhost:3000/auth/users
Accept: application/json

###
GET http://localhost:3000/auth/users?email=a@a.com
Accept: application/jso
###

GET http://localhost:3000/post

###


GET http://localhost:3000/post?sender=me

###

GET http://localhost:3000/post/62260bf39f8f7ff5c48ded71


###

POST http://localhost:3000/post
Content-Type: application/json

{
    "message" : "this is my first message",
    "sender" : "eliav2"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name" : "a",
    "email" : "a@t.com",
    "password" : "222222"
}


###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "a@t.com",
    "password" : "222222"
}

###

GET http://localhost:3000/auth/test2
